apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-z7di
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-lnnq-tenant/rhtap-demo-app/hacbs-test-project-z7di@sha256:52c566cd70a65e641c95460351da4729f70b59e1c9aedd9ca74c78783aca6be8
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
