apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-z7di
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-lnnq-tenant/rhtap-demo-app/hacbs-test-project-z7di@sha256:cc714a7e2f1f26aeba3aa3d9efefa3343f5ba2e296dc8bebdc234d507beff1ef
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
